import 'package:flutter/material.dart';

class ThemePalette {
  final String id;
  final String zhName;
  final String enName;
  final ColorScheme light;
  final ColorScheme dark;

  const ThemePalette({
    required this.id,
    required this.zhName,
    required this.enName,
    required this.light,
    required this.dark,
  });

  String get displayNameZh => zhName;
  String get displayNameEn => enName;
}

class ThemePalettes {
  static const String defaultId = 'default';
  static const String warmPaperId = 'warm_paper'; // 我们的家·暖纸/漆金
  static const String blueId = 'blue';
  static const String greenId = 'green';
  static const String purpleId = 'purple';
  static const String yellowId = 'yellow';
  static const String smokyRoseId = 'smoky_rose';
  static const String terracottaId = 'terracotta';
  static const String monochromeId = 'monochrome';
  static const String docThemeId = 'doc_theme';

  static const ThemePalette defaultPalette = ThemePalette(
    id: defaultId,
    zhName: '默认',
    enName: 'Default',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF4D5C92),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFDCE1FF),
      onPrimaryContainer: Color(0xFF03174B),
      secondary: Color(0xFF595D72),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFDEE1F9),
      onSecondaryContainer: Color(0xFF161B2C),
      tertiary: Color(0xFF75546F),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFD7F6),
      onTertiaryContainer: Color(0xFF2C122A),
      error: Color(0xFFBB0947),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFDDADE),
      onErrorContainer: Color(0xFF400013),
      surface: Color(0xFFF7F7F7),
      onSurface: Color(0xFF202020),
      onSurfaceVariant: Color(0xFF646464),
      outline: Color(0x1A000000),
      outlineVariant: Color(0xFF000000),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF121213),
      onInverseSurface: Color(0xFFF9F9F9),
      inversePrimary: Color(0xFF4D5C92),
      surfaceTint: Color(0xFF4D5C92),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFB6C4FF),
      onPrimary: Color(0xFF1D2D61),
      primaryContainer: Color(0xFF354479),
      onPrimaryContainer: Color(0xFFDCE1FF),
      secondary: Color(0xFFC2C5DD),
      onSecondary: Color(0xFF2B3042),
      secondaryContainer: Color(0xFF424659),
      onSecondaryContainer: Color(0xFFDEE1F9),
      tertiary: Color(0xFFE3BADA),
      onTertiary: Color(0xFF432740),
      tertiaryContainer: Color(0xFF5B3D57),
      onTertiaryContainer: Color(0xFFFFD7F6),
      error: Color(0xFFFCB4BD),
      onError: Color(0xFF670023),
      errorContainer: Color(0xFF910034),
      onErrorContainer: Color(0xFFFCB4BD),
      surface: Color(0xFF121213),
      onSurface: Color(0xFFF9F9F9),
      onSurfaceVariant: Color(0xFFCECECE),
      outline: Color(0x1A000000),
      outlineVariant: Color(0xFFFFFFFF),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFF7F7F7),
      onInverseSurface: Color(0xFF202020),
      inversePrimary: Color(0xFFB6C4FF),
      surfaceTint: Color(0xFFB6C4FF),
    ),
  );

  // Blue palette: derived from provided logs
  static const ThemePalette blue = ThemePalette(
    id: blueId,
    zhName: '海霄蓝',
    enName: 'Aether Blue',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF3E5E98),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFD6E2FF),
      onPrimaryContainer: Color(0xFF001A43),
      secondary: Color(0xFF575E71),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFDBE2F9),
      onSecondaryContainer: Color(0xFF131C2C),
      tertiary: Color(0xFF77517D),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFD6FF),
      onTertiaryContainer: Color(0xFF2D0D35),
      error: Color(0xFFBB0947),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFDDADE),
      onErrorContainer: Color(0xFF400013),
      surface: Color(0xFFFDFBFF),
      onSurface: Color(0xFF1B1B1D),
      onSurfaceVariant: Color(0xFF44464E),
      outline: Color(0xFF73767E),
      outlineVariant: Color(0xFFC4C6D0),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF303033),
      onInverseSurface: Color(0xFFF2F0F4),
      inversePrimary: Color(0xFFACC7FF),
      surfaceTint: Color(0xFF3E5E98),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFACC7FF),
      onPrimary: Color(0xFF032F67),
      primaryContainer: Color(0xFF24457F),
      onPrimaryContainer: Color(0xFFD6E2FF),
      secondary: Color(0xFFBFC6DC),
      onSecondary: Color(0xFF283041),
      secondaryContainer: Color(0xFF3F4758),
      onSecondaryContainer: Color(0xFFDBE2F9),
      tertiary: Color(0xFFE5B7E9),
      onTertiary: Color(0xFF44234C),
      tertiaryContainer: Color(0xFF5D3A63),
      onTertiaryContainer: Color(0xFFFFD6FF),
      error: Color(0xFFFCB4BD),
      onError: Color(0xFF670023),
      errorContainer: Color(0xFF910034),
      onErrorContainer: Color(0xFFFCB4BD),
      surface: Color(0xFF1B1B1D),
      onSurface: Color(0xFFE3E1E6),
      onSurfaceVariant: Color(0xFFC4C6D0),
      outline: Color(0xFF8E919A),
      outlineVariant: Color(0xFF44464E),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE3E1E6),
      onInverseSurface: Color(0xFF303033),
      inversePrimary: Color(0xFF3E5E98),
      surfaceTint: Color(0xFFACC7FF),
    ),
  );

  // Green palette
  static const ThemePalette green = ThemePalette(
    id: greenId,
    zhName: '竹影绿',
    enName: 'Bamboo Green',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF166C47),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFA3F4C5),
      onPrimaryContainer: Color(0xFF002111),
      secondary: Color(0xFF4E6356),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFD0E9D7),
      onSecondaryContainer: Color(0xFF0B1F15),
      tertiary: Color(0xFF22667A),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFB1EBFF),
      onTertiaryContainer: Color(0xFF001F28),
      error: Color(0xFFA63B00),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDBCF),
      onErrorContainer: Color(0xFF370E00),
      surface: Color(0xFFFBFDF8),
      onSurface: Color(0xFF191C1A),
      onSurfaceVariant: Color(0xFF404942),
      outline: Color(0xFF707871),
      outlineVariant: Color(0xFFC0C9C0),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF2E312F),
      onInverseSurface: Color(0xFFF0F1ED),
      inversePrimary: Color(0xFF87D7AA),
      surfaceTint: Color(0xFF166C47),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF87D7AA),
      onPrimary: Color(0xFF003921),
      primaryContainer: Color(0xFF005232),
      onPrimaryContainer: Color(0xFFA3F4C5),
      secondary: Color(0xFFB5CCBB),
      onSecondary: Color(0xFF203529),
      secondaryContainer: Color(0xFF374B3F),
      onSecondaryContainer: Color(0xFFD0E9D7),
      tertiary: Color(0xFF92CFE6),
      onTertiary: Color(0xFF003543),
      tertiaryContainer: Color(0xFF004E60),
      onTertiaryContainer: Color(0xFFB1EBFF),
      error: Color(0xFFFEB69A),
      onError: Color(0xFF5A1C00),
      errorContainer: Color(0xFF7F2B00),
      onErrorContainer: Color(0xFFFEB69A),
      surface: Color(0xFF191C1A),
      onSurface: Color(0xFFE1E3DF),
      onSurfaceVariant: Color(0xFFC0C9C0),
      outline: Color(0xFF8A938B),
      outlineVariant: Color(0xFF404942),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE1E3DF),
      onInverseSurface: Color(0xFF2E312F),
      inversePrimary: Color(0xFF166C47),
      surfaceTint: Color(0xFF87D7AA),
    ),
  );

  // Purple palette
  static const ThemePalette purple = ThemePalette(
    id: purpleId,
    zhName: '暮紫韵',
    enName: 'Twilight Purple',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF5D5698),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFE5DEFF),
      onPrimaryContainer: Color(0xFF190E51),
      secondary: Color(0xFF5F5C71),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFE5DFF9),
      onSecondaryContainer: Color(0xFF1B192C),
      tertiary: Color(0xFF844D69),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFD8EA),
      onTertiaryContainer: Color(0xFF350B25),
      error: Color(0xFFBB0947),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFDDADE),
      onErrorContainer: Color(0xFF400013),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF1C1B1F),
      onSurfaceVariant: Color(0xFF47464F),
      outline: Color(0xFF77757E),
      outlineVariant: Color(0xFFC9C4CF),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF313033),
      onInverseSurface: Color(0xFFF4EFF4),
      inversePrimary: Color(0xFFC8BFFF),
      surfaceTint: Color(0xFF5D5698),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFC8BFFF),
      onPrimary: Color(0xFF2E2766),
      primaryContainer: Color(0xFF453E7F),
      onPrimaryContainer: Color(0xFFE5DEFF),
      secondary: Color(0xFFC8C3DC),
      onSecondary: Color(0xFF302E42),
      secondaryContainer: Color(0xFF474459),
      onSecondaryContainer: Color(0xFFE5DFF9),
      tertiary: Color(0xFFF7B3D3),
      onTertiary: Color(0xFF4E203A),
      tertiaryContainer: Color(0xFF693651),
      onTertiaryContainer: Color(0xFFFFD8EA),
      error: Color(0xFFFCB4BD),
      onError: Color(0xFF670023),
      errorContainer: Color(0xFF910034),
      onErrorContainer: Color(0xFFFCB4BD),
      surface: Color(0xFF1C1B1F),
      onSurface: Color(0xFFE6E1E6),
      onSurfaceVariant: Color(0xFFC9C4CF),
      outline: Color(0xFF928F9A),
      outlineVariant: Color(0xFF47464F),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE6E1E6),
      onInverseSurface: Color(0xFF313033),
      inversePrimary: Color(0xFF5D5698),
      surfaceTint: Color(0xFFC8BFFF),
    ),
  );

  // Yellow palette
  static const ThemePalette yellow = ThemePalette(
    id: yellowId,
    zhName: '琥珀金',
    enName: 'Amber Gold',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF855304),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDDB6),
      onPrimaryContainer: Color(0xFF2B1700),
      secondary: Color(0xFF715A41),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFDDDBD),
      onSecondaryContainer: Color(0xFF281805),
      tertiary: Color(0xFF50652F),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFD3ECA8),
      onTertiaryContainer: Color(0xFF112000),
      error: Color(0xFFA63B00),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDBCF),
      onErrorContainer: Color(0xFF370E00),
      surface: Color(0xFFFFFBF9),
      onSurface: Color(0xFF1F1B16),
      onSurfaceVariant: Color(0xFF4F4539),
      outline: Color(0xFF817467),
      outlineVariant: Color(0xFFD4C4B4),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF35302A),
      onInverseSurface: Color(0xFFF9EFE7),
      inversePrimary: Color(0xFFFDB967),
      surfaceTint: Color(0xFF855304),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFDB967),
      onPrimary: Color(0xFF482A00),
      primaryContainer: Color(0xFF663D00),
      onPrimaryContainer: Color(0xFFFFDDB6),
      secondary: Color(0xFFDFC1A2),
      onSecondary: Color(0xFF3F2D17),
      secondaryContainer: Color(0xFF57432B),
      onSecondaryContainer: Color(0xFFFDDDBD),
      tertiary: Color(0xFFB7CF8E),
      onTertiary: Color(0xFF243605),
      tertiaryContainer: Color(0xFF3A4D1A),
      onTertiaryContainer: Color(0xFFD3ECA8),
      error: Color(0xFFFEB69A),
      onError: Color(0xFF5A1C00),
      errorContainer: Color(0xFF7F2B00),
      onErrorContainer: Color(0xFFFEB69A),
      surface: Color(0xFF1F1B16),
      onSurface: Color(0xFFEBE0D9),
      onSurfaceVariant: Color(0xFF4F4539),
      outline: Color(0xFF9D8E81),
      outlineVariant: Color(0xFF4F4539),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFEBE0D9),
      onInverseSurface: Color(0xFF35302A),
      inversePrimary: Color(0xFF855304),
      surfaceTint: Color(0xFFFDB967),
    ),
  );

  // New: Smoky Rose palette — exact values from logs
  static const ThemePalette smokyRose = ThemePalette(
    id: smokyRoseId,
    zhName: '暮霭玫',
    enName: 'Smoky Rose',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF824E6C),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFD8EA),
      onPrimaryContainer: Color(0xFF350B27),
      secondary: Color(0xFF715764),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFCD9E9),
      onSecondaryContainer: Color(0xFF291521),
      tertiary: Color(0xFF6E557D),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF3DAFF),
      onTertiaryContainer: Color(0xFF271236),
      error: Color(0xFFBB0947),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFDDADE),
      onErrorContainer: Color(0xFF400013),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF201A1D),
      onSurfaceVariant: Color(0xFF504349),
      outline: Color(0xFF82737A),
      outlineVariant: Color(0xFFD4C2C9),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF352E32),
      onInverseSurface: Color(0xFFFAEDF1),
      inversePrimary: Color(0xFFF5B3D6),
      surfaceTint: Color(0xFF824E6C),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFF5B3D6),
      onPrimary: Color(0xFF4E203C),
      primaryContainer: Color(0xFF673754),
      onPrimaryContainer: Color(0xFFFFD8EA),
      secondary: Color(0xFFDFBECD),
      onSecondary: Color(0xFF402A36),
      secondaryContainer: Color(0xFF58404C),
      onSecondaryContainer: Color(0xFFFCD9E9),
      tertiary: Color(0xFFDABCEA),
      onTertiary: Color(0xFF3D274C),
      tertiaryContainer: Color(0xFF553E64),
      onTertiaryContainer: Color(0xFFF3DAFF),
      error: Color(0xFFFCB4BD),
      onError: Color(0xFF670023),
      errorContainer: Color(0xFF910034),
      onErrorContainer: Color(0xFFFCB4BD),
      surface: Color(0xFF201A1D),
      onSurface: Color(0xFFECDFE3),
      onSurfaceVariant: Color(0xFFD4C2C9),
      outline: Color(0xFF9D8C93),
      outlineVariant: Color(0xFF504349),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFECDFE3),
      onInverseSurface: Color(0xFF352E32),
      inversePrimary: Color(0xFF824E6C),
      surfaceTint: Color(0xFFF5B3D6),
    ),
  );

  // New: Terracotta Clay palette — exact values from logs
  static const ThemePalette terracotta = ThemePalette(
    id: terracottaId,
    zhName: '陶砂红',
    enName: 'Terracotta Clay',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF8B4E3B),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDBD0),
      onPrimaryContainer: Color(0xFF370D02),
      secondary: Color(0xFF77574D),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDBD0),
      onSecondaryContainer: Color(0xFF2C160E),
      tertiary: Color(0xFF745B25),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFDEA3),
      onTertiaryContainer: Color(0xFF261900),
      error: Color(0xFFB91F01),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD3),
      onErrorContainer: Color(0xFF3E0400),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF221A18),
      onSurfaceVariant: Color(0xFF53433E),
      outline: Color(0xFF86736D),
      outlineVariant: Color(0xFFD9C2BB),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF372E2C),
      onInverseSurface: Color(0xFFFDEDE9),
      inversePrimary: Color(0xFFFFB59E),
      surfaceTint: Color(0xFF8B4E3B),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB59E),
      onPrimary: Color(0xFF522211),
      primaryContainer: Color(0xFF6E3725),
      onPrimaryContainer: Color(0xFFFFDBD0),
      secondary: Color(0xFFE7BDB1),
      onSecondary: Color(0xFF442A22),
      secondaryContainer: Color(0xFF5D4037),
      onSecondaryContainer: Color(0xFFFFDBD0),
      tertiary: Color(0xFFE4C282),
      onTertiary: Color(0xFF402D00),
      tertiaryContainer: Color(0xFF5A430F),
      onTertiaryContainer: Color(0xFFFFDEA3),
      error: Color(0xFFFFB5A5),
      onError: Color(0xFF650C00),
      errorContainer: Color(0xFF8D1600),
      onErrorContainer: Color(0xFFFFB5A5),
      surface: Color(0xFF221A18),
      onSurface: Color(0xFFEFDFDB),
      onSurfaceVariant: Color(0xFFD9C2BB),
      outline: Color(0xFFA18C86),
      outlineVariant: Color(0xFF53433E),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFEFDFDB),
      onInverseSurface: Color(0xFF372E2C),
      inversePrimary: Color(0xFF8B4E3B),
      surfaceTint: Color(0xFFFFB59E),
    ),
  );

  static const ThemePalette monochrome = ThemePalette(
    id: monochromeId,
    zhName: '纸墨灰',
    enName: 'Frost Gray',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF000000),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFEFEFEF),
      onPrimaryContainer: Color(0xFF000000),
      secondary: Color(0xFF1A1A1A),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFF4F4F4),
      onSecondaryContainer: Color(0xFF000000),
      tertiary: Color(0xFF2E2E2E),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF7F7F7),
      onTertiaryContainer: Color(0xFF000000),
      error: Color(0xFF000000),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFEAEAEA),
      onErrorContainer: Color(0xFF000000),
      surface: Color(0xFFF7F7F7),
      onSurface: Color(0xFF202020),
      onSurfaceVariant: Color(0xFF646464),
      outline: Color(0x1A000000),
      outlineVariant: Color(0xFF000000),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF121213),
      onInverseSurface: Color(0xFFF9F9F9),
      inversePrimary: Color(0xFFFFFFFF),
      surfaceTint: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFFFFF),
      onPrimary: Color(0xFF000000),
      primaryContainer: Color(0xFF2B2B2B),
      onPrimaryContainer: Color(0xFFFFFFFF),
      secondary: Color(0xFFE0E0E0),
      onSecondary: Color(0xFF000000),
      secondaryContainer: Color(0xFF242424),
      onSecondaryContainer: Color(0xFFE0E0E0),
      tertiary: Color(0xFFCCCCCC),
      onTertiary: Color(0xFF000000),
      tertiaryContainer: Color(0xFF1F1F1F),
      onTertiaryContainer: Color(0xFFFFFFFF),
      error: Color(0xFFFFFFFF),
      onError: Color(0xFF000000),
      errorContainer: Color(0xFF333333),
      onErrorContainer: Color(0xFFFFFFFF),
      surface: Color(0xFF121213),
      onSurface: Color(0xFFF9F9F9),
      onSurfaceVariant: Color(0xFFCECECE),
      outline: Color(0x1A000000),
      outlineVariant: Color(0xFFFFFFFF),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFF7F7F7),
      onInverseSurface: Color(0xFF202020),
      inversePrimary: Color(0xFF000000),
      surfaceTint: Color(0xFFFFFFFF),
    ),
  );

  // New: Document Theme palette based on provided spec
  static const ThemePalette docTheme = ThemePalette(
    id: docThemeId,
    zhName: '樱桃绿',
    enName: 'Verdant Mint',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF00B96B),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0x3349E6A2),
      onPrimaryContainer: Color(0xFF003921),
      secondary: Color(0xFF509177),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0x33509177),
      onSecondaryContainer: Color(0xFF003823),
      tertiary: Color(0xFF9C96F9),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0x339C96F9),
      onTertiaryContainer: Color(0xFF2C122A),
      error: Color(0xFFFF0000),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0x1AFF0000),
      onErrorContainer: Color(0xFFFF0000),
      surface: Color(0xFFF7F7F7),
      onSurface: Color(0xFF202020),
      onSurfaceVariant: Color(0xFF646464),
      outline: Color(0x1A000000),
      outlineVariant: Color(0xFF000000),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF121213),
      onInverseSurface: Color(0xFFF9F9F9),
      inversePrimary: Color(0xFF00B96B),
      surfaceTint: Color(0xFF00B96B),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF00B96B),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0x3300B96B),
      onPrimaryContainer: Color(0xFF003921),
      secondary: Color(0xFFB4D7C6),
      onSecondary: Color(0xFF204D39),
      secondaryContainer: Color(0x33B4D7C6),
      onSecondaryContainer: Color(0xFF0B3A27),
      tertiary: Color(0xFFB5AFFD),
      onTertiary: Color(0xFF000000),
      tertiaryContainer: Color(0x33B5AFFD),
      onTertiaryContainer: Color(0xFF2D0D35),
      error: Color(0xFFFF0000),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0x1AFF0000),
      onErrorContainer: Color(0xFFFF0000),
      surface: Color(0xFF121213),
      onSurface: Color(0xFFF9F9F9),
      onSurfaceVariant: Color(0xFFCECECE),
      outline: Color(0x1A000000),
      outlineVariant: Color(0xFFFFFFFF),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFF7F7F7),
      onInverseSurface: Color(0xFF202020),
      inversePrimary: Color(0xFF00B96B),
      surfaceTint: Color(0xFF00B96B),
    ),
  );
  // 我们的家 · 暖纸/漆金（纸感底、墨色字、珊瑚 primary、漆金 tertiary）
  static const ThemePalette warmPaper = ThemePalette(
    id: warmPaperId,
    zhName: '暖纸',
    enName: 'Warm Paper',
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFAA5D3C), // coral-deep
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFF3DACE), // 珊瑚浅染（气泡/高亮底）
      onPrimaryContainer: Color(0xFF4A2418),
      secondary: Color(0xFF6D6456), // soft
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFECE3D6),
      onSecondaryContainer: Color(0xFF2A241B),
      tertiary: Color(0xFFB0894E), // gold
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF0E2C4),
      onTertiaryContainer: Color(0xFF3A2C12),
      error: Color(0xFFB3261E),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFF9DEDC),
      onErrorContainer: Color(0xFF410E0B),
      surface: Color(0xFFFAF6ED), // paper
      onSurface: Color(0xFF33302A), // ink
      onSurfaceVariant: Color(0xFF6D6456),
      outline: Color(0xFFB7AD9A),
      outlineVariant: Color(0xFFE3D9C9),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF33302A),
      onInverseSurface: Color(0xFFFAF6ED),
      inversePrimary: Color(0xFFDDA07E),
      surfaceTint: Color(0xFFAA5D3C),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFDD8D6F), // coral (night)
      onPrimary: Color(0xFF3A1E12),
      primaryContainer: Color(0xFF4A2E20),
      onPrimaryContainer: Color(0xFFF7D9C8),
      secondary: Color(0xFFB5AB97), // soft (night)
      onSecondary: Color(0xFF2A241B),
      secondaryContainer: Color(0xFF38322A),
      onSecondaryContainer: Color(0xFFE8DECB),
      tertiary: Color(0xFFCDA35E), // gold (night)
      onTertiary: Color(0xFF3A2C12),
      tertiaryContainer: Color(0xFF4A3A1E),
      onTertiaryContainer: Color(0xFFF0E2C4),
      error: Color(0xFFF2B8B5),
      onError: Color(0xFF601410),
      errorContainer: Color(0xFF8C1D18),
      onErrorContainer: Color(0xFFF9DEDC),
      surface: Color(0xFF18140F), // warm near-black（非冷黑）
      onSurface: Color(0xFFF1E9DA), // ink (night)
      onSurfaceVariant: Color(0xFFB5AB97),
      outline: Color(0xFF6E6555),
      outlineVariant: Color(0xFF4A4339),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFF1E9DA),
      onInverseSurface: Color(0xFF2A241B),
      inversePrimary: Color(0xFFAA5D3C),
      surfaceTint: Color(0xFFDD8D6F),
    ),
  );

  // ===== 我们的家·全套皮肤（从招牌色种子生成整套 ColorScheme）=====
  // 种子：primary(招牌色) / tertiary(漆金) / surface / onSurface(墨) / onSurfaceVariant(soft)。
  // 容器/描边/反色由种子推导，省去手写每套 30 个字段。源自 home.html 各 data-palette。
  static ColorScheme _scheme(
    Brightness b,
    Color primary,
    Color tertiary,
    Color surface,
    Color onSurface,
    Color onVariant,
  ) {
    final dark = b == Brightness.dark;
    Color lerp(Color a, Color c, double t) => Color.lerp(a, c, t)!;
    Color onOf(Color c) =>
        c.computeLuminance() > 0.55 ? const Color(0xFF2A1A12) : Colors.white;
    return ColorScheme(
      brightness: b,
      primary: primary,
      onPrimary: onOf(primary),
      primaryContainer: lerp(surface, primary, dark ? 0.30 : 0.20),
      onPrimaryContainer: onSurface,
      secondary: onVariant,
      onSecondary: dark ? const Color(0xFF221E18) : Colors.white,
      secondaryContainer: lerp(surface, onVariant, dark ? 0.22 : 0.16),
      onSecondaryContainer: onSurface,
      tertiary: tertiary,
      onTertiary: onOf(tertiary),
      tertiaryContainer: lerp(surface, tertiary, dark ? 0.28 : 0.20),
      onTertiaryContainer: onSurface,
      error: dark ? const Color(0xFFF2B8B5) : const Color(0xFFB3261E),
      onError: dark ? const Color(0xFF601410) : Colors.white,
      errorContainer: dark ? const Color(0xFF8C1D18) : const Color(0xFFF9DEDC),
      onErrorContainer: dark
          ? const Color(0xFFF9DEDC)
          : const Color(0xFF410E0B),
      surface: surface,
      onSurface: onSurface,
      onSurfaceVariant: onVariant,
      outline: lerp(surface, onSurface, dark ? 0.34 : 0.32),
      outlineVariant: lerp(surface, onSurface, dark ? 0.16 : 0.12),
      shadow: const Color(0xFF000000),
      scrim: const Color(0xFF000000),
      inverseSurface: onSurface,
      onInverseSurface: surface,
      inversePrimary: primary,
      surfaceTint: primary,
    );
  }

  static ThemePalette _home(
    String id,
    String zh,
    String en, {
    required Color pL,
    required Color tL,
    required Color sL,
    required Color iL,
    required Color vL,
    required Color pD,
    required Color tD,
    required Color sD,
    required Color iD,
    required Color vD,
  }) {
    return ThemePalette(
      id: id,
      zhName: zh,
      enName: en,
      light: _scheme(Brightness.light, pL, tL, sL, iL, vL),
      dark: _scheme(Brightness.dark, pD, tD, sD, iD, vD),
    );
  }

  static final ThemePalette macaron = _home(
    'macaron',
    '马卡龙',
    'Macaron',
    pL: const Color(0xFFC2734F),
    tL: const Color(0xFFB0894E),
    sL: const Color(0xFFFDFBF8),
    iL: const Color(0xFF33302A),
    vL: const Color(0xFF6D6456),
    pD: const Color(0xFFE2A3B0),
    tD: const Color(0xFFCAB47E),
    sD: const Color(0xFF141A26),
    iD: const Color(0xFFE9EEF8),
    vD: const Color(0xFFA9B3C9),
  );
  static final ThemePalette peach = _home(
    'peach',
    '蜜桃',
    'Peach',
    pL: const Color(0xFFD9774A),
    tL: const Color(0xFFB0894E),
    sL: const Color(0xFFFEFAF6),
    iL: const Color(0xFF33302A),
    vL: const Color(0xFF6D6456),
    pD: const Color(0xFFEFA278),
    tD: const Color(0xFFDFB47E),
    sD: const Color(0xFF1A1410),
    iD: const Color(0xFFF6ECE1),
    vD: const Color(0xFFC3AE9B),
  );
  static final ThemePalette mint = _home(
    'mint',
    '薄荷',
    'Mint',
    pL: const Color(0xFF3F9E82),
    tL: const Color(0xFF8FA85E),
    sL: const Color(0xFFF6FBF6),
    iL: const Color(0xFF33302A),
    vL: const Color(0xFF6D6456),
    pD: const Color(0xFF86CFBD),
    tD: const Color(0xFFBCCD8E),
    sD: const Color(0xFF0F181B),
    iD: const Color(0xFFE6F1EE),
    vD: const Color(0xFFA2BFBA),
  );
  static final ThemePalette lavender = _home(
    'lavender',
    '薰衣草',
    'Lavender',
    pL: const Color(0xFF8A6FC0),
    tL: const Color(0xFF9D7FB0),
    sL: const Color(0xFFFBF8FC),
    iL: const Color(0xFF33302A),
    vL: const Color(0xFF6D6456),
    pD: const Color(0xFFCDA6E4),
    tD: const Color(0xFFC6B4E6),
    sD: const Color(0xFF16131F),
    iD: const Color(0xFFECE8F6),
    vD: const Color(0xFFB2AAC8),
  );
  static final ThemePalette sky = _home(
    'sky',
    '天青',
    'Sky',
    pL: const Color(0xFF5B83C4),
    tL: const Color(0xFF7E98CA),
    sL: const Color(0xFFF6FAFD),
    iL: const Color(0xFF33302A),
    vL: const Color(0xFF6D6456),
    pD: const Color(0xFF92B4E2),
    tD: const Color(0xFFB4BFDA),
    sD: const Color(0xFF0B0E16),
    iD: const Color(0xFFDFE7F5),
    vD: const Color(0xFF9FAFCC),
  );
  static final ThemePalette milk = _home(
    'milk',
    '燕麦奶',
    'Oat Milk',
    pL: const Color(0xFFB58A66),
    tL: const Color(0xFFB08F44),
    sL: const Color(0xFFFDFCFA),
    iL: const Color(0xFF4A463F),
    vL: const Color(0xFF7A7160),
    pD: const Color(0xFFD2A68A),
    tD: const Color(0xFFC4AE84),
    sD: const Color(0xFF171513),
    iD: const Color(0xFFF0EAE0),
    vD: const Color(0xFFB8AE9E),
  );
  static final ThemePalette morandi = _home(
    'morandi',
    '莫兰迪',
    'Morandi',
    pL: const Color(0xFF9A7263),
    tL: const Color(0xFF9C8D63),
    sL: const Color(0xFFF3F1EC),
    iL: const Color(0xFF4A463F),
    vL: const Color(0xFF7D776C),
    pD: const Color(0xFFC2A298),
    tD: const Color(0xFFB3A682),
    sD: const Color(0xFF16171A),
    iD: const Color(0xFFE6E6E3),
    vD: const Color(0xFFA8A8A2),
  );
  static final ThemePalette rococo = _home(
    'rococo',
    '洛可可',
    'Rococo',
    pL: const Color(0xFFC16A78),
    tL: const Color(0xFFBC8E54),
    sL: const Color(0xFFFCF4F1),
    iL: const Color(0xFF5A3F44),
    vL: const Color(0xFF8A6A6A),
    pD: const Color(0xFFE698A8),
    tD: const Color(0xFFD9B07A),
    sD: const Color(0xFF1A1217),
    iD: const Color(0xFFF5E7EB),
    vD: const Color(0xFFC3A5B0),
  );
  static final ThemePalette memphis = _home(
    'memphis',
    '孟菲斯',
    'Memphis',
    pL: const Color(0xFFE8512F),
    tL: const Color(0xFFE0A21E),
    sL: const Color(0xFFFDFBF4),
    iL: const Color(0xFF27241F),
    vL: const Color(0xFF5A5249),
    pD: const Color(0xFF5FAEF8),
    tD: const Color(0xFFF2C75E),
    sD: const Color(0xFF0D1524),
    iD: const Color(0xFFE9F1FC),
    vD: const Color(0xFFA6BAD8),
  );
  static final ThemePalette dopamine = _home(
    'dopamine',
    '多巴胺',
    'Dopamine',
    pL: const Color(0xFFF0563A),
    tL: const Color(0xFFE8A41E),
    sL: const Color(0xFFFFFDF5),
    iL: const Color(0xFF2C2820),
    vL: const Color(0xFF5E574B),
    pD: const Color(0xFFF0904E),
    tD: const Color(0xFFF0C24A),
    sD: const Color(0xFF101B2C),
    iD: const Color(0xFFF1EEE4),
    vD: const Color(0xFFB4BAC0),
  );
  static final ThemePalette whitegold = _home(
    'whitegold',
    '白金',
    'White Gold',
    pL: const Color(0xFFB0923C),
    tL: const Color(0xFF9A7C32),
    sL: const Color(0xFFFDFBF6),
    iL: const Color(0xFF3A352A),
    vL: const Color(0xFF7A7160),
    pD: const Color(0xFFDDC065),
    tD: const Color(0xFFE6C75E),
    sD: const Color(0xFF14110B),
    iD: const Color(0xFFF3ECD6),
    vD: const Color(0xFFC6BA92),
  );

  static final List<ThemePalette> all = <ThemePalette>[
    macaron,
    peach,
    mint,
    lavender,
    sky,
    milk,
    morandi,
    rococo,
    whitegold,
    memphis,
    dopamine,
    warmPaper,
    defaultPalette,
    blue,
    green,
    purple,
    yellow,
    smokyRose,
    terracotta,
    monochrome,
    docTheme,
  ];

  static ThemePalette byId(String id) {
    return all.firstWhere((p) => p.id == id, orElse: () => defaultPalette);
  }
}
